modLoader = "javafml"
loaderVersion = "[46,)"
license = "GPL-3.0"

[[mods]]
modId = "splasher"
version = "${version}"
displayName = "Splasher for Forge"
displayURL = "https://github.com/KessokuTeaTime/Splasher"
authors = "Kessoku Tea Time"
description = '''
Why Don't Splash?
'''
logoFile = "icon.png"

[[dependencies.splasher]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.splasher]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.splasher]]
modId = "architectury"
mandatory = true
versionRange = "[9,)"
ordering = "AFTER"
side = "BOTH"