[versions]
maven-group = "band.kessokuteatime"
archives-name = "splasher"
mod = "6.2.4"

minecraft = "26.2"
java = "25"

architectury-plugin = "3.5.169"
architectury-loom = "1.17.491"
shadow = "9.6.0"
modpublisher = "2.2.1"

fabric-loader = "0.19.3"
fabric-minecraft-range = "~26.2"
javafml = "3"
neoforge = "26.2.0.25-beta"
neoforge-range = "[26.2.0.25-beta,)"
neoforge-minecraft-range = "[26.2,26.3)"

cloth-config = "26.2.155"
modmenu = "20.0.1"
bounced = "4.1.4"

id-modrinth = "4yIZUuyx"
id-curseforge = "844451"

display-name = "Splasher!"

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
neoforge = { group = "net.neoforged", name = "neoforge", version.ref = "neoforge" }

cloth-config = { group = "me.shedaniel.cloth", name = "cloth-config", version.ref = "cloth-config" }
cloth-config-fabric = { group = "me.shedaniel.cloth", name = "cloth-config-fabric", version.ref = "cloth-config" }
cloth-config-neoforge = { group = "me.shedaniel.cloth", name = "cloth-config-neoforge", version.ref = "cloth-config" }
modmenu = { group = "com.terraformersmc", name = "modmenu", version.ref = "modmenu" }

[plugins]
architectury = { id = "architectury-plugin", version.ref = "architectury-plugin" }
architectury-loom = { id = "dev.architectury.loom-no-remap", version.ref = "architectury-loom" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
modpublisher = { id = "com.hypherionmc.modutils.modpublisher", version.ref = "modpublisher" }
